graphhopper/jsprit

jsprit-core/src/main/java/jsprit/core/reporting/SolutionPrinter.java
Solution printer was able to write only on the System.out. 
I simply added the possibility to write on any PrintWriter stream.
For this I made all public methods an overloaded form with one additional PrintWriter parameter.
The original functions now work like this:
// Wrapping System.out into a PrintWriter
private static final PrintWriter SYSTEM_OUT_AS_PRINT_WRITER = new PrintWriter(System.out);
public static void print(VehicleRoutingProblemSolution solution) {
print(SYSTEM_OUT_AS_PRINT_WRITER, solution);
SYSTEM_OUT_AS_PRINT_WRITER.flush();
}
If you would like to use it in any other way, you can use the extended version. For example, to get the output into a String:
StringWriter sw = new StringWriter();
PrintWriter pw = new PrintWriter(sw);
SolutionPrinter.print(pw, solution);
String …
=> SolutionPrinter able to print into any PrintWriter stream

jsprit-core/src/main/java/jsprit/core/algorithm/io/AlgorithmConfigXmlReader.java, jsprit-core/src/main/java/jsprit/core/algorithm/io/VehicleRoutingAlgorithms.java, jsprit-core/src/main/java/jsprit/core/algorithm/recreate/BestInsertionConcurrent.java, jsprit-core/src/main/java/jsprit/core/problem/io/VrpXMLReader.java, jsprit-core/src/main/java/jsprit/core/problem/io/VrpXMLWriter.java, jsprit-instances/src/main/java/jsprit/instance/reader/ChristofidesReader.java, jsprit-instances/src/main/java/jsprit/instance/reader/CordeauReader.java, jsprit-instances/src/main/java/jsprit/instance/reader/LiLimReader.java, jsprit-instances/src/main/java/jsprit/instance/reader/LopezIbanezBlumReader.java, jsprit-instances/src/main/java/jsprit/instance/reader/LuiShenReader.java, jsprit-instances/src/main/java/jsprit/instance/reader/SolomonReader.java, jsprit-instances/src/main/java/jsprit/instance/reader/VrphGoldenReader.java
Most calls were replaced by Runtime exceptions. This gives the client
some opportunity to respond to the exceptions.
There definitely is more room for improvement but I think this is a good start.
=> Removed all System.exit() calls (related to #182)

WHATS_NEW.md
Just noticed this in passing whilst checking out the docs for the new version.
=> Fix links in what's new

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/io/VrpXMLReader.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/io/VrpXMLWriter.java, jsprit-core/src/main/resources/vrp_xml_schema.xsd
https://github.com/graphhopper/jsprit/issues/208
I'm on it ;)
=> Add breaks to xml writer/reader

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/io/VrpXMLReader.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/io/VrpXMLWriter.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/solution/route/VehicleRoute.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/SolutionPrinter.java, jsprit-core/src/main/resources/vrp_xml_schema.xsd
It brings some fixes to breaks into XML operations
=> Refine Breaks XML

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/io/VrpXMLReader.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/io/VrpXMLWriter.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/FastVehicleRoutingTransportCostsMatrix.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/VehicleRoutingTransportCostsMatrix.java, jsprit-core/src/main/resources/vrp_xml_schema.xsd
Add : 
- CostPerServiceTime
- CostPerWaitingTime
Replace : 
- CostPerTime -> CostPerTransportTime
=> Add some costs into XML

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/io/VrpXMLWriter.java
Currently it writes as much solution as there is room in memory + 1.
But in some case only the best one is needed.
=> XMLWriter : have choice to only display the best solution

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/io/VrpXMLWriter.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/SolutionPrinter.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/VehicleIndexComparator.java
Have the same vehicle order in input and in output
=> Solution with initial vehicle order

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/ruin/ClusterRuinStrategyFactory.java, jsprit-io/src/main/java/com/graphhopper/jsprit/io/algorithm/VehicleRoutingAlgorithms.java, jsprit-io/src/main/resources/algorithm_schema.xsd
clusterRuin is currently unavailable using the xml definition of the algorithm
=> Add clusterRuin to xml algorithm config

jsprit-io/src/main/java/com/graphhopper/jsprit/io/algorithm/VehicleRoutingAlgorithms.java
This fix the issue I mentioned yesterday : 
https://github.com/graphhopper/jsprit/issues/264
=> CoreConstraint at xml creation

jsprit-io/src/main/java/com/graphhopper/jsprit/io/problem/VrpXMLReader.java, jsprit-io/src/main/java/com/graphhopper/jsprit/io/problem/VrpXMLWriter.java, jsprit-io/src/main/resources/vrp_xml_schema.xsd
VrpXMLWriter is a fix, currently it write 'serviceId' instead of 'breakId'.
Others are in order to define its own id to each break, with the idea to handle with multiple breaks for each vehicle.
=> breakId fix & custom

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/GeneralJobInsertionCalculator.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/AbstractListBackedJobActivityList.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/solution/route/activity/JobActivity.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/GeneralJobInsertionWithServicesTest.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/GeneralJobInsertionWithShipmentsTest.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/testutils/NewActivityFactory.java
Somehow the pull request was not created a few hours ago.
=> orderNumber added

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/LocalActivityInsertionCostsCalculator.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/TestLocalActivityInsertionCostsCalculator.java
see [discussions here](https://discuss.graphhopper.com/t/returning-non-optimal-solution-when-vehicle-start-end-locations-are-not-the-same/1061).
#280
=> fix bug 280

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/SizeDimension.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/problem/SizeDimensionTest.java
Sorry. That's why we make tests. I forgot. :-(
=> Fixed SizeDimension.sign() bug.

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/MaxDistanceConstraint.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/problem/constraint/VehicleDependentTraveledDistanceTest.java
this PR does the same thing as #301, without the state(manager) simplification.
so also related to #292.
=> fix deliverShipment insertion in max distance constraint

jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/AbstractPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/SolutionPrinter.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/columndefinition/HumanReadableDurationFormatter.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/route/AbstractDurationPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/route/WaitingDurationPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/AbstractVehicleDurationPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/AbstractVehicleTimeWindowPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleActiveDurationPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleActivityCountPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleActivityTypeCountPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleAllActivityTypeCountPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleDriverNamePrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleIdleDurationPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleOperationDurationPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleRouteDurationPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleRouteNumberPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleRouteTimeWindowPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleShiftDurationPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleShiftTimeWindowPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleStatisticsContext.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleSummaryColumnLists.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleSummaryContext.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleTravelDurationPrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleTruckNamePrinterColumn.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/reporting/vehicle/VehicleTypePrinterColumn.java
This is my last piece for SolutionPrinter refactor: 
I added another table to print. It is called VehicleSummary and calculates some statistics per route level:
- static info, such as vehicle and driver data 
- number of activities (total, by type)
- durations: 
- total route
- shift
- break
- travel
- operation
- idle
- each duration could be displayed as
- numeric
- human readable
- percentage of route time
- percentage of shift time
It uses the ConfigurableTablePrinter structure, so the user can define what to see and supports excel export.
I kept the old print() functions in SolutionPrinter, but introduced new ones: I broke the output into segments (summary, routeDetails and vehicleSummary as for now) and each gets its own printXXX methods. It is much cleaner and requires not too much …
=> Vehicle summary

README.md
#335 Fixed
Just small mistake correct it.
=> Markdown syntax correct

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/VehicleRoutingAlgorithm.java
Now the bug is fixed.
However, there are a few more things in `verify` we should do:
- Check if vehicles from the route are there in the new problem (throw exception)
- Remove all jobs not in the new problem, but in the initital solution route
=> #354 - Initial solution with new jobs added

jsprit-io/src/main/java/com/graphhopper/jsprit/io/problem/VrpXMLWriter.java, jsprit-io/src/test/java/com/graphhopper/jsprit/io/problem/VrpXMLWriterTest.java
Add basic test to check that two outputs are the same
Refactored and cleaned-up other tests a bit
=> Add VrpXMLWriter method that returns OutputStream

README.md
Sorry I just clicked and got 404.
Now I think all fixed.
=> One more get disconnected.

jsprit-analysis/src/main/java/com/graphhopper/jsprit/analysis/toolbox/Plotter.java
Heroku read-only policy needs this modification. I intended to use this brilliant API, so for displaying the image, I return the instance of the file, convert to base64 and send to my client in Angular 2. 
Used on: https://github.com/albertjimenez/cvrptenis
=> Modified signature for returning the file instance 

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/cost/AbstractForwardVehicleRoutingTransportCosts.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/cost/VehicleRoutingTransportCosts.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/CrowFlyCosts.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/EuclideanCosts.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/FastVehicleRoutingTransportCostsMatrix.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/GreatCircleCosts.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/ManhattanCosts.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/VehicleRoutingTransportCostsMatrix.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/CVRPwithMatrix_IT.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/CapacityConstraint_IT.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/VariableDepartureAndWaitingTime_IT.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/TestCalculatesServiceInsertion.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/recreate/TestCalculatesServiceInsertionOnRouteLevel.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/ruin/distance/TestJobDistanceAvgCosts.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/analysis/SolutionAnalyserTest.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/problem/VehicleRoutingProblemTest.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/problem/constraint/VehicleDependentTraveledDistanceTest.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/util/UnassignedJobReasonTrackerTest.java, jsprit-examples/src/main/java/com/graphhopper/jsprit/examples/BuildAlgorithmFromScratch.java, jsprit-examples/src/main/java/com/graphhopper/jsprit/examples/MultipleTimeWindowExample2.java, jsprit-examples/src/main/java/com/graphhopper/jsprit/examples/PickupAndDeliveryExample.java, jsprit-examples/src/main/java/com/graphhopper/jsprit/examples/VRPWithBackhaulsExample2.java, jsprit-instances/src/main/java/com/graphhopper/jsprit/instance/reader/Figliozzi.java
#290 
btw, do we need something like get backward distance?
=> make VehicleRoutingTransportCosts implement TransportDistance

.travis.yml, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/Service.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/Shipment.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/EuclideanCosts.java, jsprit-examples/.gitignore
EuclideanCosts.calculateDistance(Location,Location) -- throws NullPointerException anyway, so no need to throw it explicitly => reduced to a one-liner.
`Skills.addSkill(String)` does `skill.trim().toLowerCase()`, so `Skills.containsSkill(String)` should also do both (not only `skill.toLowerCase()`)
=> small refinements

jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/VehicleRoutingProblem.java, jsprit-instances/src/main/java/com/graphhopper/jsprit/instance/reader/BelhaizaReader.java, jsprit-instances/src/main/java/com/graphhopper/jsprit/instance/reader/LuiShenReader.java
Should I also rename LuiShenReader to LiuShenReader?
=> changes in jsprit-instance readers

jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/CrowFlyCosts.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/util/EuclideanCosts.java
Inherintance works better than delegation due to speedFactor and speed being public.
=> CrowFlyCosts inherits from EuclideanCosts to remove duplicated code

docs/Getting-Started.md
removed html escaping for markdown
=> updated getting started to fix formatting

.travis.yml
Have added a variable "EMAIL" to the travis settings that you can easily change.
=> Hide email due to spamming

jsprit-analysis/src/main/java/com/graphhopper/jsprit/analysis/toolbox/GraphStreamViewer.java, jsprit-analysis/src/main/java/com/graphhopper/jsprit/analysis/toolbox/Plotter.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/VehicleRoutingAlgorithm.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/ruin/RuinWorst.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/VehicleRoutingProblem.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/MaxDistanceConstraint.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/Service.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/Shipment.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/solution/route/VehicleRoute.java
Brought to you by Einride, www.einride.tech :smiley:
=> Fixes/enhancements (mostly) about non-job activities

jsprit-analysis/src/main/java/com/graphhopper/jsprit/analysis/toolbox/Plotter.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/AlgorithmUtil.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/module/RuinAndRecreateModule.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/DefaultScorer.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/recreate/LocalActivityInsertionCostsCalculator.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/ruin/JobNeighborhoodsOptimized.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/ruin/RuinClusters.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/ruin/RuinRadial.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/ruin/RuinRandom.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/ruin/RuinWorst.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/state/UpdateActivityNextLocations.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/state/UpdateActivityPrevLocations.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/VehicleRoutingProblem.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/constraint/VehicleDependentTimeWindowConstraints.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/job/Service.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/solution/route/activity/ActWithoutStaticLocation.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/solution/route/activity/DefaultTourActivityFactory.java, jsprit-core/src/main/java/com/graphhopper/jsprit/core/problem/solution/route/activity/ServiceActivity.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/problem/VehicleRoutingProblemTest.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/problem/job/ServiceTest.java, jsprit-examples/src/main/java/com/graphhopper/jsprit/examples/SimpleExampleWithoutLocation.java, jsprit-examples/src/main/java/com/graphhopper/jsprit/examples/SimpleWithoutLocationExample2.java
This allows to add an arbitrary number of services/activities without a static location. Thus, it allows to model multiple breaks, multiple telcos etc..
=> WIP: Activities without static location

jsprit-core/src/main/java/com/graphhopper/jsprit/core/algorithm/ruin/JobNeighborhoodsImpl.java, jsprit-core/src/test/java/com/graphhopper/jsprit/core/algorithm/ruin/JobNeighborhoodsImplTest.java
Instead of returning the max distance it is returning 0.
Is there any specific reason?
=> Return maxDistance instead of 0
